#ifndef STATEMACHINESTATES_H
#define STATEMACHINESTATES_H

#define SM_STATE_NOTMAL 0
#define SM_STATE_SAMPLINGRATE_ADJUSTING 1
#define SM_STATE_GAIN_ADJUSTING 2
#define SM_STATE_TIMESPAN_ADJUSTING 3

#endif // STATEMACHINESTATES_H
